#!/bin/bash

# 品优购项目 - 快速启动指南

echo "========================================"
echo "  品优购项目 - 快速启动指南"
echo "========================================"
echo ""

echo "📋 服务端口清单:"
echo "----------------------------------------"
echo "基础设施:"
echo "  - MySQL:       3306"
echo "  - Redis:       6379"
echo "  - Zookeeper:   2181"
echo "  - Solr:        8983"
echo "  - ActiveMQ:    61616 (管理台 8161)"
echo ""
echo "Service 层:"
echo "  - 商品服务:    9001"
echo "  - 内容服务:    9002"
echo "  - 用户服务:    9003"
echo "  - 订单服务:    9004"
echo "  - 购物车服务:  9005"
echo "  - 搜索服务:    9006"
echo "  - 页面服务:    9007"
echo "  - 支付服务:    9008"
echo "  - 秒杀服务:    9009"
echo ""
echo "Web 层:"
echo "  - 运营后台:    9101"
echo "  - 门户前台:    9103"
echo "  - 用户中心:    9104"
echo "  - 搜索页面:    9105"
echo "  - 商家后台:    9106"
echo ""

echo "🚀 启动顺序:"
echo "----------------------------------------"
echo "1. 启动基础设施 (MySQL → Redis → Zookeeper → Solr → ActiveMQ)"
echo "2. 启动 Service 层 (9001-9009)"
echo "3. 启动 Web 层 (9101-9106)"
echo ""

echo "📝 推荐启动方式:"
echo "----------------------------------------"
echo "方式一: 使用 IntelliJ IDEA (推荐)"
echo "  1. 打开项目"
echo "  2. 找到 Application 启动类"
echo "  3. 右键 → Run 'Application'"
echo ""

echo "方式二: 使用 Maven"
echo "  mvn spring-boot:run -pl <module-name>"
echo ""

echo "📚 相关文档:"
echo "  - 环境搭建: docs/环境搭建指南.md"
echo "  - 测试计划: docs/接口测试计划.md"
echo "  - 数据库设计: docs/数据库设计说明.md"
echo "  - 开发规范: docs/开发规范.md"
echo ""

echo "🔧 常用命令:"
echo "  # 检查基础设施"
echo "  bash scripts/test-infrastructure.sh"
echo ""
echo "  # 测试 Service 接口"
echo "  bash scripts/test-service-apis.sh"
echo ""
echo "  # 运行所有测试"
echo "  bash scripts/run-all-tests.sh"
echo ""

echo "========================================"
